# Generated by Django 5.0.1 on 2025-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_alter_suscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='True si es una suscripción automática'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='preapproval_id',
            field=models.CharField(blank=True, help_text='ID del preapproval de MercadoPago', max_length=100, null=True),
        ),
    ]
