# Generated by Django 5.0.1 on 2025-09-29 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_add_recurring_subscription_fields'),
        ('usuarios', '0013_perfil_latitud_perfil_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPlanProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField(help_text='Fecha en que se aplicará el cambio')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('es_upgrade', models.BooleanField(default=False, help_text='True si es upgrade, False si es downgrade')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el cambio')),
                ('plan_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_desde', to='usuarios.plan')),
                ('plan_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_hacia', to='usuarios.plan')),
                ('suscripcion_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_programados', to='suscripciones.suscripcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de Plan Programado',
                'verbose_name_plural': 'Cambios de Plan Programados',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
