FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Variables de entorno para testing
ARG API_URL
ENV VITE_API_URL=$API_URL
ENV VITE_NODE_ENV=test
ARG LANDING_ONLY_MODE=false
ENV VITE_LANDING_ONLY_MODE=$LANDING_ONLY_MODE
ARG GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID

# Puerto para testing
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
