FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Variables de entorno para desarrollo
ENV VITE_API_URL=http://localhost:8001/api
ENV VITE_NODE_ENV=development
ARG LANDING_ONLY_MODE=false
ENV VITE_LANDING_ONLY_MODE=$LANDING_ONLY_MODE

# Puerto para desarrollo
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
