version: '3'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DB_MYSQL_HOST=${NPM_DB_HOST:-db-nginx}
      - DB_MYSQL_PORT=${NPM_DB_PORT:-3306}
      - DB_MYSQL_USER=${NPM_DB_USER:-npm}
      - DB_MYSQL_PASSWORD=${NPM_DB_PASSWORD:-npm}
      - DB_MYSQL_NAME=${NPM_DB_NAME:-npm}
    volumes:
      - ./data/nginx/config:/data
      - ./data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - proxy_network
      - deconfianza_dev_network
      - deconfianza_test_network
      - deconfianza_prod_network
    depends_on:
      - db-nginx

  db-nginx:
    image: 'mariadb:latest'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${NPM_MYSQL_ROOT_PASSWORD:-npm}
      - MYSQL_DATABASE=${NPM_DB_NAME:-npm}
      - MYSQL_USER=${NPM_DB_USER:-npm}
      - MYSQL_PASSWORD=${NPM_DB_PASSWORD:-npm}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
  deconfianza_dev_network:
    external: true
  deconfianza_test_network:
    external: true
  deconfianza_prod_network:
    external: true