# Generated by Django 5.0.1 on 2025-09-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_plan_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='plan',
            name='max_images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_videos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
