# Generated by Django 5.0.1 on 2025-09-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0003_alter_plan_options_plan_max_images_plan_max_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.categoria'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.rubro'),
        ),
    ]
