# Generated by Django 5.0.1 on 2025-09-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_categoria_perfil_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio mensual en pesos argentinos', max_digits=10),
        ),
    ]
