# Generated by Django 5.0.1 on 2025-09-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_plan_precio_mensual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='benefits',
        ),
    ]
