# Generated by Django 5.0.1 on 2025-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_plan_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_servicios',
            field=models.PositiveIntegerField(default=1, help_text='Número máximo de servicios que puede crear'),
        ),
        migrations.AddField(
            model_name='plan',
            name='puede_crear_servicios',
            field=models.BooleanField(default=True, help_text='Permite crear servicios personalizados'),
        ),
        migrations.AddField(
            model_name='plan',
            name='puede_recibir_resenas',
            field=models.BooleanField(default=True, help_text='Permite recibir y mostrar reseñas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='puede_subir_media',
            field=models.BooleanField(default=True, help_text='Permite subir fotos y videos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='puede_ver_estadisticas',
            field=models.BooleanField(default=True, help_text='Permite ver estadísticas detalladas'),
        ),
    ]
