# Generated by Django 5.0.1 on 2025-09-21 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_plan_max_servicios_plan_puede_crear_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan de suscripción del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.plan'),
        ),
    ]
