# Generated by Django 5.0.1 on 2025-09-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_convert_plan_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='social_id',
            field=models.CharField(blank=True, help_text='ID de la cuenta social (Google, Facebook, etc.)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='social_provider',
            field=models.CharField(blank=True, help_text='Proveedor social (google, facebook, etc.)', max_length=50, null=True),
        ),
    ]
