# Generated by Django 5.0.1 on 2025-09-26 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_perfil_social_id_perfil_social_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='plan',
        ),
        migrations.AddField(
            model_name='perfil',
            name='plan_legacy',
            field=models.ForeignKey(blank=True, help_text='Plan de suscripción del usuario - DEPRECATED', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.plan'),
        ),
    ]
