# Generated by Django 5.0.1 on 2025-09-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_rename_plan_to_plan_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='plan_legacy',
        ),
    ]
