# Generated by Django 5.0.1 on 2025-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_plan_legacy_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del prestador'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='Sitio web del prestador'),
        ),
    ]
