# Generated by Django 5.0.1 on 2025-09-20 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='RangoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rango', models.IntegerField(choices=[(1, 'Rango 1 - Gratuito'), (2, 'Rango 2 - Básico'), (3, 'Rango 3 - Premium'), (4, 'Rango 4 - Destacado')], unique=True)),
                ('precio_usd', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('descripcion', models.TextField()),
                ('limite_imagenes', models.IntegerField(default=0)),
                ('limite_videos', models.IntegerField(default=0)),
                ('permite_resenas', models.BooleanField(default=False)),
                ('asesoria_empresarial', models.BooleanField(default=False)),
                ('acceso_informes', models.BooleanField(default=False)),
                ('posicion_destacada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rango de Suscripción',
                'verbose_name_plural': 'Rangos de Suscripción',
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('sitio_web', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('redes_sociales', models.JSONField(blank=True, default=dict)),
                ('fecha_inicio_suscripcion', models.DateField(blank=True, null=True)),
                ('fecha_fin_suscripcion', models.DateField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('mision', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('valores', models.TextField(blank=True)),
                ('tarifario', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rango_suscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.rangosuscripcion')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
            },
        ),
        migrations.CreateModel(
            name='MediaPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='prestadores/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='servicios.prestador')),
            ],
            options={
                'verbose_name': 'Media del Prestador',
                'verbose_name_plural': 'Media de los Prestadores',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='servicios.prestador')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='servicios.categoria')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='servicios.rubro')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AddField(
            model_name='prestador',
            name='servicios',
            field=models.ManyToManyField(related_name='prestadores', to='servicios.servicio'),
        ),
        migrations.CreateModel(
            name='ServicioPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_prestador', to=settings.AUTH_USER_MODEL)),
                ('servicio_base', models.ForeignKey(blank=True, help_text='Servicio del catálogo como referencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio del Prestador',
                'verbose_name_plural': 'Servicios de los Prestadores',
            },
        ),
    ]
