# Generated by Django 5.0.1 on 2025-09-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacionPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to='servicios.prestador')),
            ],
            options={
                'verbose_name': 'Visualización de Perfil',
                'verbose_name_plural': 'Visualizaciones de Perfiles',
            },
        ),
    ]
