# Generated by Django 5.0.1 on 2025-09-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_visualizacionperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='rango_suscripcion',
        ),
        migrations.DeleteModel(
            name='RangoSuscripcion',
        ),
    ]
