# Generated by Django 5.0.1 on 2025-09-22 00:01

from django.db import migrations, models


def clear_servicios(apps, schema_editor):
    """Eliminar todos los servicios existentes para permitir campos obligatorios"""
    Servicio = apps.get_model('servicios', 'Servicio')
    Servicio.objects.all().delete()


def reverse_clear_servicios(apps, schema_editor):
    """Función reversa - no hacer nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_remove_prestador_servicios_servicio_activo_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_servicios, reverse_clear_servicios),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='servicios', to='servicios.categoria'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='prestador',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='servicios_creados', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='rubro',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='servicios', to='servicios.rubro'),
        ),
    ]
