# Generated by Django 5.0.1 on 2025-09-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20250921_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='tarifario',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='valores',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='vision',
        ),
    ]
