# Generated by Django 5.0.1 on 2025-09-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_remove_unused_prestador_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='rubro',
        ),
    ]
