# Generated by Django 5.0.1 on 2025-09-29 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_remove_categoria_rubro_from_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizacionperfil',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='mediaprestador',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='prestador',
        ),
        migrations.AddField(
            model_name='mediaprestador',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_prestador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visualizacionperfil',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Prestador',
        ),
    ]
